In [1]:
import pandas as pd

df = pd.read_csv("../data/processed/processed_data.csv")

df.head()

,TransactionId,BatchId,AccountId,SubscriptionId,CustomerId,CurrencyCode,CountryCode,ProviderId,ProductId,ProductCategory,ChannelId,Amount,Value,TransactionStartTime,PricingStrategy,FraudResult,is_high_risk
0,TransactionId_76871,BatchId_36123,AccountId_3957,SubscriptionId_887,CustomerId_4406,UGX,256,ProviderId_6,ProductId_10,airtime,ChannelId_3,1000.0,1000,2018-11-15 02:18:49+00:00,2,0,0
1,TransactionId_73770,BatchId_15642,AccountId_4841,SubscriptionId_3829,CustomerId_4406,UGX,256,ProviderId_4,ProductId_6,financial_services,ChannelId_2,-20.0,20,2018-11-15 02:19:08+00:00,2,0,0
2,TransactionId_26203,BatchId_53941,AccountId_4229,SubscriptionId_222,CustomerId_4683,UGX,256,ProviderId_6,ProductId_1,airtime,ChannelId_3,500.0,500,2018-11-15 02:44:21+00:00,2,0,1
3,TransactionId_380,BatchId_102363,AccountId_648,SubscriptionId_2185,CustomerId_988,UGX,256,ProviderId_1,ProductId_21,utility_bill,ChannelId_3,20000.0,21800,2018-11-15 03:32:55+00:00,2,0,0
4,TransactionId_28195,BatchId_38780,AccountId_4841,SubscriptionId_3829,CustomerId_988,UGX,256,ProviderId_4,ProductId_6,financial_services,ChannelId_2,-644.0,644,2018-11-15 03:34:21+00:00,2,0,0

In [2]:
y = df["is_high_risk"]

In [3]:
X = df.drop(
    columns=[
        "is_high_risk"
    ]
)

In [4]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [5]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(
    max_iter=1000
)

lr.fit(
    X_train,
    y_train
)

ValueError: could not convert string to float: 'TransactionId_40796'

In [6]:
print(X_train.dtypes)

TransactionId            object
BatchId                  object
AccountId                object
SubscriptionId           object
CustomerId               object
CurrencyCode             object
CountryCode               int64
ProviderId               object
ProductId                object
ProductCategory          object
ChannelId                object
Amount                  float64
Value                     int64
TransactionStartTime     object
PricingStrategy           int64
FraudResult               int64
dtype: object

In [7]:
df = df.drop(
    columns=[
        "TransactionId",
        "BatchId",
        "AccountId",
        "SubscriptionId",
        "CustomerId"
    ]
)

In [8]:
df["TransactionStartTime"] = pd.to_datetime(
    df["TransactionStartTime"]
)

df["TransactionHour"] = df["TransactionStartTime"].dt.hour
df["TransactionDay"] = df["TransactionStartTime"].dt.day
df["TransactionMonth"] = df["TransactionStartTime"].dt.month

df.drop(
    columns=["TransactionStartTime"],
    inplace=True
)

In [9]:
categorical_cols = [
    "CurrencyCode",
    "ProviderId",
    "ProductId",
    "ProductCategory",
    "ChannelId"
]

df = pd.get_dummies(
    df,
    columns=categorical_cols,
    drop_first=True
)

In [10]:
X = df.drop(
    columns=["is_high_risk"]
)

y = df["is_high_risk"]

In [11]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [12]:
print(X_train.select_dtypes(include="object").columns)

Index([], dtype='object')

In [13]:
print(X.shape)
print(y.value_counts())

(95662, 46)
is_high_risk
0    84636
1    11026
Name: count, dtype: int64

In [14]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [15]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(
    max_iter=1000,
    random_state=42
)

lr.fit(
    X_train,
    y_train
)

c:\Users\3440\Downloads\credit-risk-model\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=1000, random_state=42)

In [16]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

lr_preds = lr.predict(X_test)

print(
    "Accuracy:",
    accuracy_score(y_test, lr_preds)
)

print(
    "Precision:",
    precision_score(y_test, lr_preds)
)

print(
    "Recall:",
    recall_score(y_test, lr_preds)
)

print(
    "F1:",
    f1_score(y_test, lr_preds)
)

print(
    "ROC-AUC:",
    roc_auc_score(y_test, lr_preds)
)

Accuracy: 0.8847540897925051
Precision: 0.0
Recall: 0.0
F1: 0.0
ROC-AUC: 0.5

c:\Users\3440\Downloads\credit-risk-model\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [17]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

rf.fit(
    X_train,
    y_train
)

rf_preds = rf.predict(X_test)

In [18]:
print(
    "Accuracy:",
    accuracy_score(y_test, rf_preds)
)

print(
    "Precision:",
    precision_score(y_test, rf_preds)
)

print(
    "Recall:",
    recall_score(y_test, rf_preds)
)

print(
    "F1:",
    f1_score(y_test, rf_preds)
)

print(
    "ROC-AUC:",
    roc_auc_score(y_test, rf_preds)
)

Accuracy: 0.8887785501489573
Precision: 0.5258215962441315
Recall: 0.35555555555555557
F1: 0.42424242424242425
ROC-AUC: 0.6568952163411048

In [19]:
results = pd.DataFrame({
    "Model": [
        "Logistic Regression",
        "Random Forest"
    ],
    "Accuracy": [
        lr_accuracy,
        rf_accuracy
    ],
    "Precision": [
        lr_precision,
        rf_precision
    ],
    "Recall": [
        lr_recall,
        rf_recall
    ],
    "F1": [
        lr_f1,
        rf_f1
    ],
    "ROC-AUC": [
        lr_auc,
        rf_auc
    ]
})

results

NameError: name 'lr_accuracy' is not defined

In [20]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

lr_accuracy = accuracy_score(y_test, lr_preds)
lr_precision = precision_score(y_test, lr_preds)
lr_recall = recall_score(y_test, lr_preds)
lr_f1 = f1_score(y_test, lr_preds)
lr_auc = roc_auc_score(y_test, lr_preds)

print("Accuracy:", lr_accuracy)
print("Precision:", lr_precision)
print("Recall:", lr_recall)
print("F1:", lr_f1)
print("ROC-AUC:", lr_auc)

Accuracy: 0.8847540897925051
Precision: 0.0
Recall: 0.0
F1: 0.0
ROC-AUC: 0.5

c:\Users\3440\Downloads\credit-risk-model\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [21]:
rf_accuracy = accuracy_score(y_test, rf_preds)
rf_precision = precision_score(y_test, rf_preds)
rf_recall = recall_score(y_test, rf_preds)
rf_f1 = f1_score(y_test, rf_preds)
rf_auc = roc_auc_score(y_test, rf_preds)

print("Accuracy:", rf_accuracy)
print("Precision:", rf_precision)
print("Recall:", rf_recall)
print("F1:", rf_f1)
print("ROC-AUC:", rf_auc)

Accuracy: 0.8887785501489573
Precision: 0.5258215962441315
Recall: 0.35555555555555557
F1: 0.42424242424242425
ROC-AUC: 0.6568952163411048

In [22]:
import pandas as pd

results = pd.DataFrame({
    "Model": [
        "Logistic Regression",
        "Random Forest"
    ],
    "Accuracy": [
        lr_accuracy,
        rf_accuracy
    ],
    "Precision": [
        lr_precision,
        rf_precision
    ],
    "Recall": [
        lr_recall,
        rf_recall
    ],
    "F1": [
        lr_f1,
        rf_f1
    ],
    "ROC-AUC": [
        lr_auc,
        rf_auc
    ]
})

results

                 Model  Accuracy  Precision    Recall        F1   ROC-AUC
0  Logistic Regression  0.884754   0.000000  0.000000  0.000000  0.500000
1        Random Forest  0.888779   0.525822  0.355556  0.424242  0.656895

In [24]:
rf_preds = rf.predict(X_test)

rf_probs = rf.predict_proba(X_test)[:,1]

In [25]:
rf_accuracy = accuracy_score(
    y_test,
    rf_preds
)

rf_precision = precision_score(
    y_test,
    rf_preds
)

rf_recall = recall_score(
    y_test,
    rf_preds
)

rf_f1 = f1_score(
    y_test,
    rf_preds
)

rf_auc = roc_auc_score(
    y_test,
    rf_probs
)

In [26]:
from sklearn.model_selection import GridSearchCV

param_grid = {

    "n_estimators": [100, 200],

    "max_depth": [
        5,
        10,
        None
    ]
}

In [27]:
grid = GridSearchCV(
    RandomForestClassifier(
        random_state=42
    ),
    param_grid,
    cv=3,
    scoring="roc_auc"
)

grid.fit(
    X_train,
    y_train
)

GridSearchCV(cv=3, estimator=RandomForestClassifier(random_state=42),
             param_grid={'max_depth': [5, 10, None],
                         'n_estimators': [100, 200]},
             scoring='roc_auc')

In [28]:
best_rf = grid.best_estimator_

print(grid.best_params_)

{'max_depth': None, 'n_estimators': 200}

In [29]:
import mlflow

In [31]:
mlflow.set_tracking_uri("http://127.0.0.1:5000")
mlflow.set_experiment(
    "Credit Risk Model"
)

with mlflow.start_run():

    mlflow.log_param(
        "model",
        "RandomForest"
    )

    mlflow.log_metric(
        "accuracy",
        rf_accuracy
    )

    mlflow.log_metric(
        "precision",
        rf_precision
    )

    mlflow.log_metric(
        "recall",
        rf_recall
    )

    mlflow.log_metric(
        "f1",
        rf_f1
    )

    mlflow.log_metric(
        "roc_auc",
        rf_auc
    )

2026/06/03 16:41:59 INFO mlflow.tracking.fluent: Experiment with name 'Credit Risk Model' does not exist. Creating a new experiment.

🏃 View run casual-fly-64 at: http://127.0.0.1:5000/#/experiments/1/runs/ea519b5d451e41c88be525a333b9768b
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1